sonar.projectKey=maiwei-app_workflows
sonar.organization=maiwei-app

sonar.issue.ignore.multicriteria=s7637
sonar.issue.ignore.multicriteria.s7637.ruleKey=S7637
sonar.issue.ignore.multicriteria.s7637.resourceKey=.github/workflows/*
