name: YAML Schema & Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install yamllint
        run: |
          pip install yamllint --only-binary :all:

      - name: Lint YAML syntax
        run: yamllint -d relaxed .github/workflows/

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.0'

      - name: Install actionlint
        run: |
          curl -sL --proto-redir =https https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash -o download-actionlint.bash
          sha256sum -c <<< "a96d60132afb74536ff2b55cc784d5c55b0b57980d3d49f962f0b3871447d53a  download-actionlint.bash" || exit 1
          bash download-actionlint.bash
          echo "${PWD}" >> $GITHUB_PATH

      - name: Validate GitHub Actions workflows
        run: ./actionlint -format sarif -output ./results.sarif .github/workflows/ || true

  sonar:
    needs: quality
    uses: maiwei-app/workflows/.github/workflows/sonar-scan.yml@feat/ci-yaml-schema-linter
    with:
      project-key: maiwei-app_workflows
      sonar-organization: maiwei-app
