name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  yaml-testing:
    uses: maiwei-app/workflows/.github/workflows/lint-yaml.yml@main

  quality-gate:
    needs: yaml-testing
    uses: maiwei-app/workflows/.github/workflows/sonar-scan.yml@main
    with:
      project-key: maiwei-app_workflows
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
