name: Conventional Commits

on:
  pull_request:
    branches: [main]
  workflow_call: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commits (conventional commits)
        uses: wagoid/commitlint-github-action@v6
