name: Lint YAML

on:
  workflow_call: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install 'yamllint==1.38.0' --only-binary :all:

      - name: Lint YAML
        run: yamllint -d relaxed --no-warnings .
