name: Sonar scan

on:
  workflow_call:
    inputs:
      project-key:
        type: string
        required: true
      sonar-organization:
        type: string
        required: false
        default: maiwei-app
    secrets:
      sonar-token:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        with:
          args: >
            -Dsonar.organization=${{ inputs.sonar-organization }}
            -Dsonar.projectKey=${{ inputs.project-key }}
